---
- name: import package task
  ansible.builtin.import_tasks:
    file: package.yml
  tags:
    - role_influxdb_package
- name: import service task
  ansible.builtin.import_tasks:
    file: service.yml
  tags:
    - role_influxdb_service
