---
- name: restart inflexdb
  ansible.builtin.systemd_service:
    state: restarted
    name: inflexdb
- name: reload inflexdb
  ansible.builtin.systemd_service:
    state: reloaded
    name: inflexdb
