---
- name: Verify
  hosts: all
  gather_facts: true
  check_mode: true
  tasks:
    - name: test apt signing key
      ansible.builtin.apt_key:
        url: https://repos.influxdata.com/influxdb.key
        state: present
      register: result
    - name: assert apt signing key
      ansible.builtin.assert:
        that: result is not changed
    - name: test repository
      ansible.builtin.apt_repository:
        filename: influxdb
        repo: deb https://repos.influxdata.com/debian {{ ansible_facts.distribution_release }} stable
        state: present
      register: result
    - name: assert repository
      ansible.builtin.assert:
        that: result is not changed
    - name: test package
      ansible.builtin.apt:
        name: influxdb2
      register: result
    - name: assert package
      ansible.builtin.assert:
        that: result is not changed
    # - name: test service
    #   ansible.builtin.systemd:
    #     name: influxdb
    #     state: started
    #     enabled: true
    #   register: result
    # - name: assert service
    #   ansible.builtin.assert:
    #     that: result is not changed
